name: Deploy to Cloud Run (OIDC)

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  PROJECT_ID_NUMBER: ${{ secrets.GCP_PROJECT_ID_NUMBER }}
  REGION: us-central1
  SERVICE: networksecurity-ml
  REPO: networksecurity-ml
  IMAGE: networksecurity-ml-image

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Test OIDC auth
        run: |
          gcloud auth list
          gcloud auth print-access-token

      - name: Build image
        run: |
          docker build -t \
          $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA .

      - name: Push image
        run: |
          docker push \
          $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
